# Sobre a qualidade do dataset

O dataset de vendas não apresenta valores nulos ou quebrados.
O dataset de produtos apresenta, mas ao realizarmos o merge para analisar o faturamento dos produtos, vemos que nenhum desses produtos foi vendido no período, dispensando assim o tratamento dos dados.

In [2]:
import pandas as pd

In [3]:
base = pd.read_csv('data/vendas.csv')
base_produtos = pd.read_csv('data/produto.csv')
base

,COD_ATEND,COD_VENDA,COD_FILIAL,FILIAL,DATA_ATEND,SKU,UNID,QTD_VENDA,FATUR_VENDA,CLI_CPF
0,000304564.299.0101042.20240102,000304564.299.0101042.20240102.000009.02,101042,SHOPPING,2024-01-02,9,KG,0.258,18.04,ec0abf3f4220
1,000374698.258.0101032.20240102,000374698.258.0101032.20240102.000009.10,101032,RUA,2024-01-02,9,KG,0.064,4.50,83d596ee0acf
2,000383551.256.0101032.20240102,000383551.256.0101032.20240102.000009.02,101032,RUA,2024-01-02,9,KG,0.164,11.49,46f63c18e055
3,000383533.256.0101032.20240102,000383533.256.0101032.20240102.000009.02,101032,RUA,2024-01-02,9,KG,0.202,14.13,6def1d35e2fe
4,000432095.257.0101032.20240102,000432095.257.0101032.20240102.000051.06,101032,RUA,2024-01-02,51,KG,0.086,6.87,1576e1a36394
...,...,...,...,...,...,...,...,...,...,...
556193,000396872.299.0101042.20241231,000396872.299.0101042.20241231.024706.03,101042,SHOPPING,2024-12-31,24706,KG,0.172,15.46,1137731f4e6d
556194,000503471.257.0101032.20241231,000503471.257.0101032.20241231.024706.05,101032,RUA,2024-12-31,24706,KG,0.149,13.40,450e762ff3dc
556195,000396715.299.0101042.20241231,000396715.299.0101042.20241231.024706.01,101042,SHOPPING,2024-12-31,24706,KG,0.198,17.80,7c8d2e4be303
556196,000402593.298.0101042.20241231,000402593.298.0101042.20241231.024706.03,101042,SHOPPING,2024-12-31,24706,KG,0.244,21.94,f16ad4e37bb5
556197,000503479.257.0101032.20241231,000503479.257.0101032.20241231.024706.02,101032,RUA,2024-12-31,24706,KG,0.184,16.54,b07b21397e0a

In [4]:
base_produtos

,SKU,NOME_PRODUTO,CATEGORIA,SUBCATEGORIA
0,3.0,COCO RALADO GROSSO KG ...,Doceria,Confeitaria
1,4.0,ICE TEA LEAO LATA 340ML ...,NaN,NaN
2,5.0,TAHINE ISTAMBUL 200G ...,Pelo Mundo,Pastas Árabes
3,6.0,AMENDOIM MOIDO KG ...,Castanhas & Oleaginosas,Oleaginosas moídas
4,7.0,HALAWI ISTAMBUL LATA 500G ...,Pelo Mundo,Pastas Árabes
...,...,...,...,...
6495,171874.0,BARRA BOLD BAR BANOFFEE 60G NV ...,Suplementos,Barrinhas
6496,171877.0,VINHO CASIL.D.CARNAVAL SPECTACULAR CARBENET 75...,Vinhos & Espumantes,Tintos
6497,171878.0,VINHO CASIL.D.CARNAVAL FANTASTIC SWEET 750ML C...,Vinhos & Espumantes,Tintos
6498,171887.0,BATATA PALHA EXTRA FINA VISCONTI 100G ...,Biscoitos,Batatas palhas
6499,NaN,NaN,NaN,NaN

In [5]:
base.info()

<class 'pandas.DataFrame'>
RangeIndex: 556198 entries, 0 to 556197
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   COD_ATEND    556198 non-null  str
 1   COD_VENDA    556198 non-null  str
 2   COD_FILIAL   556198 non-null  int64
 3   FILIAL       556198 non-null  str
 4   DATA_ATEND   556198 non-null  str
 5   SKU          556198 non-null  int64
 6   UNID         556198 non-null  str
 7   QTD_VENDA    556198 non-null  float64
 8   FATUR_VENDA  556198 non-null  float64
 9   CLI_CPF      556198 non-null  str
dtypes: float64(2), int64(2), str(6)
memory usage: 42.4 MB

In [6]:
base.describe()

          COD_FILIAL            SKU      QTD_VENDA    FATUR_VENDA
count  556198.000000  556198.000000  556198.000000  556198.000000
mean   101036.799028    6180.184127       0.280890      14.111390
std         4.995964    6854.352241       0.516884      29.043274
min    101032.000000       9.000000       0.002000       0.030000
25%    101032.000000     264.000000       0.102000       4.470000
50%    101032.000000    2987.000000       0.154000       7.820000
75%    101042.000000   13778.000000       0.269000      14.260000
max    101042.000000   24706.000000     100.700000    4994.760000

In [7]:
base_produtos.info()

<class 'pandas.DataFrame'>
RangeIndex: 6500 entries, 0 to 6499
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SKU           6499 non-null   float64
 1   NOME_PRODUTO  6499 non-null   str
 2   CATEGORIA     4498 non-null   str
 3   SUBCATEGORIA  4498 non-null   str
dtypes: float64(1), str(3)
memory usage: 203.3 KB

# Hipóteses

| Hipótese | Explicação |
| -- | -- |
| H1: de passagem e desengajados| Entre os clientes em churn, há clientes de passagem, que compraram uma única vez, e há clientes que tiveram mais de uma compra e se desengajaram.|
| H2.1: frequência | O intervalo de compra (inter-purchase time) entre clientes desengajados aumenta até que efetivamente entrem em churn|
| H2.2: comportamental | A categoria influencia o churn (exemplo: clientes que compram itens do dia a dia, arroz e feijão, fazem a compra do mês e são mais fidelizados)|
| H2.3: feriados | Meses com mais feriados são meses que mais clientes voltam|
| H3: tipo de filial | O tipo de filial influencia a taxa de churn |

# Validação da definição de churn

Definimos um cliente em churn como um cliente com mais de 90 dias desde a data da sua última compra.

Para validar isso, vamos checar quantos % das compras reocorrem dentro de 90 dias.

In [8]:
base
# uma linha pra cada produto -> data_atend repetido para uma única compra
# uma pequena subhipótese - um cliente nunca faz mais de uma compra no mesmo dia

,COD_ATEND,COD_VENDA,COD_FILIAL,FILIAL,DATA_ATEND,SKU,UNID,QTD_VENDA,FATUR_VENDA,CLI_CPF
0,000304564.299.0101042.20240102,000304564.299.0101042.20240102.000009.02,101042,SHOPPING,2024-01-02,9,KG,0.258,18.04,ec0abf3f4220
1,000374698.258.0101032.20240102,000374698.258.0101032.20240102.000009.10,101032,RUA,2024-01-02,9,KG,0.064,4.50,83d596ee0acf
2,000383551.256.0101032.20240102,000383551.256.0101032.20240102.000009.02,101032,RUA,2024-01-02,9,KG,0.164,11.49,46f63c18e055
3,000383533.256.0101032.20240102,000383533.256.0101032.20240102.000009.02,101032,RUA,2024-01-02,9,KG,0.202,14.13,6def1d35e2fe
4,000432095.257.0101032.20240102,000432095.257.0101032.20240102.000051.06,101032,RUA,2024-01-02,51,KG,0.086,6.87,1576e1a36394
...,...,...,...,...,...,...,...,...,...,...
556193,000396872.299.0101042.20241231,000396872.299.0101042.20241231.024706.03,101042,SHOPPING,2024-12-31,24706,KG,0.172,15.46,1137731f4e6d
556194,000503471.257.0101032.20241231,000503471.257.0101032.20241231.024706.05,101032,RUA,2024-12-31,24706,KG,0.149,13.40,450e762ff3dc
556195,000396715.299.0101042.20241231,000396715.299.0101042.20241231.024706.01,101042,SHOPPING,2024-12-31,24706,KG,0.198,17.80,7c8d2e4be303
556196,000402593.298.0101042.20241231,000402593.298.0101042.20241231.024706.03,101042,SHOPPING,2024-12-31,24706,KG,0.244,21.94,f16ad4e37bb5
556197,000503479.257.0101032.20241231,000503479.257.0101032.20241231.024706.02,101032,RUA,2024-12-31,24706,KG,0.184,16.54,b07b21397e0a

In [9]:
# agrupando clientes pelo numero de visitas
visitas = base.groupby('CLI_CPF')['DATA_ATEND'].nunique()
visitas

CLI_CPF
000068324b7a     7
0000e45cf057     1
0002f692edec     7
0003384bf59a     1
0005526cbd58     2
                ..
fffc253c49e5     1
fffc424374da    11
fffcf6606169     1
fffd5abaf0a9     1
fffe8a47ed47     1
Name: DATA_ATEND, Length: 102943, dtype: int64

In [10]:
one_timers = visitas[visitas == 1]
one_timers

CLI_CPF
0000e45cf057    1
0003384bf59a    1
00067e2e7ba6    1
000703991686    1
00087ede2f36    1
               ..
fffb246bc503    1
fffc253c49e5    1
fffcf6606169    1
fffd5abaf0a9    1
fffe8a47ed47    1
Name: DATA_ATEND, Length: 51678, dtype: int64

In [11]:
drop = base[base['CLI_CPF'].isin(one_timers.index)]


base_recurring = base.drop(drop.index)

base_recurring

,COD_ATEND,COD_VENDA,COD_FILIAL,FILIAL,DATA_ATEND,SKU,UNID,QTD_VENDA,FATUR_VENDA,CLI_CPF
0,000304564.299.0101042.20240102,000304564.299.0101042.20240102.000009.02,101042,SHOPPING,2024-01-02,9,KG,0.258,18.04,ec0abf3f4220
3,000383533.256.0101032.20240102,000383533.256.0101032.20240102.000009.02,101032,RUA,2024-01-02,9,KG,0.202,14.13,6def1d35e2fe
4,000432095.257.0101032.20240102,000432095.257.0101032.20240102.000051.06,101032,RUA,2024-01-02,51,KG,0.086,6.87,1576e1a36394
5,000374626.258.0101032.20240102,000374626.258.0101032.20240102.000051.03,101032,RUA,2024-01-02,51,KG,0.062,4.95,ac98260ec312
6,000264675.297.0101042.20240102,000264675.297.0101042.20240102.000051.01,101042,SHOPPING,2024-01-02,51,KG,0.198,15.82,d57b8a74e61e
...,...,...,...,...,...,...,...,...,...,...
556193,000396872.299.0101042.20241231,000396872.299.0101042.20241231.024706.03,101042,SHOPPING,2024-12-31,24706,KG,0.172,15.46,1137731f4e6d
556194,000503471.257.0101032.20241231,000503471.257.0101032.20241231.024706.05,101032,RUA,2024-12-31,24706,KG,0.149,13.40,450e762ff3dc
556195,000396715.299.0101042.20241231,000396715.299.0101042.20241231.024706.01,101042,SHOPPING,2024-12-31,24706,KG,0.198,17.80,7c8d2e4be303
556196,000402593.298.0101042.20241231,000402593.298.0101042.20241231.024706.03,101042,SHOPPING,2024-12-31,24706,KG,0.244,21.94,f16ad4e37bb5
556197,000503479.257.0101032.20241231,000503479.257.0101032.20241231.024706.02,101032,RUA,2024-12-31,24706,KG,0.184,16.54,b07b21397e0a

In [12]:
n_visitas_recurring = base_recurring.groupby('CLI_CPF')['DATA_ATEND'].nunique()
n_visitas_recurring

CLI_CPF
000068324b7a     7
0002f692edec     7
0005526cbd58     2
00059c6f012d     2
0005e6437ac2     5
                ..
fffa15bae441     4
fffaaeb82ced     3
fffb1d44408d    10
fffb8c945b57    19
fffc424374da    11
Name: DATA_ATEND, Length: 51265, dtype: int64

In [13]:
# sanity check
51265+51678==102943

True

In [14]:
# calcular inter puchase time
base_recurring['DATA_ATEND'] = pd.to_datetime(base_recurring['DATA_ATEND'])

visitas_recurring = base_recurring[['CLI_CPF', 'DATA_ATEND']].drop_duplicates().sort_values(['CLI_CPF', 'DATA_ATEND'])

visitas_recurring

             CLI_CPF DATA_ATEND
21138   000068324b7a 2024-01-18
63230   000068324b7a 2024-02-20
97691   000068324b7a 2024-03-14
233921  000068324b7a 2024-06-15
257006  000068324b7a 2024-07-02
...              ...        ...
347569  fffc424374da 2024-08-28
412710  fffc424374da 2024-10-07
424433  fffc424374da 2024-10-14
488462  fffc424374da 2024-11-23
549574  fffc424374da 2024-12-27

[245579 rows x 2 columns]

In [15]:
visitas_recurring['intervalo'] = visitas_recurring.groupby('CLI_CPF')['DATA_ATEND'].diff().dt.days


# dropando primeira compra (sem intervalo anterior)
intervalos = visitas_recurring['intervalo'].dropna()

intervalos

63230     33.0
97691     23.0
233921    93.0
257006    17.0
320827    39.0
          ...
347569    30.0
412710    40.0
424433     7.0
488462    40.0
549574    34.0
Name: intervalo, Length: 194314, dtype: float64

In [16]:
intervalos.quantile([0.25, 0.5, 0.75, 0.9])

0.25     14.0
0.50     29.0
0.75     63.0
0.90    119.0
Name: intervalo, dtype: float64

In [17]:
print(f'% das recompras em até 90 dias: {(intervalos<90).mean() * 100 :.2f} %')

% das recompras em até 90 dias: 83.88 %

# H1: entre os clientes em churn num dado momento, há uma parcela de passagem e há clientes verdadeiramente desengejados

In [18]:
# calcular quantos clientes em churn no ultimo dia do ano, quantos desses são one-timers e quanto sao recorrentes
base['DATA_ATEND'] = pd.to_datetime(base['DATA_ATEND'])
max_date = base['DATA_ATEND'].max()

threshold = max_date - pd.Timedelta(days=90)

threshold

Timestamp('2024-10-02 00:00:00')

In [19]:
resumo_clientes = base.groupby('CLI_CPF').agg(visitas = ('DATA_ATEND', 'nunique'), ultima_compra= ('DATA_ATEND', 'max'))
resumo_clientes

              visitas ultima_compra
CLI_CPF
000068324b7a        7    2024-10-26
0000e45cf057        1    2024-09-22
0002f692edec        7    2024-10-22
0003384bf59a        1    2024-10-29
0005526cbd58        2    2024-08-31
...               ...           ...
fffc253c49e5        1    2024-08-10
fffc424374da       11    2024-12-27
fffcf6606169        1    2024-02-04
fffd5abaf0a9        1    2024-12-08
fffe8a47ed47        1    2024-11-29

[102943 rows x 2 columns]

In [20]:
resumo_clientes['churn'] = resumo_clientes['ultima_compra'] < threshold
resumo_clientes['tipo'] = resumo_clientes['visitas'].apply(lambda x: 'one timer' if x == 1 else 'recurring')
resumo_clientes

              visitas ultima_compra  churn       tipo
CLI_CPF
000068324b7a        7    2024-10-26  False  recurring
0000e45cf057        1    2024-09-22   True  one timer
0002f692edec        7    2024-10-22  False  recurring
0003384bf59a        1    2024-10-29  False  one timer
0005526cbd58        2    2024-08-31   True  recurring
...               ...           ...    ...        ...
fffc253c49e5        1    2024-08-10   True  one timer
fffc424374da       11    2024-12-27  False  recurring
fffcf6606169        1    2024-02-04   True  one timer
fffd5abaf0a9        1    2024-12-08  False  one timer
fffe8a47ed47        1    2024-11-29  False  one timer

[102943 rows x 4 columns]

In [21]:
churn_df = resumo_clientes[resumo_clientes['churn']]
print(churn_df['tipo'].value_counts())
print(churn_df['tipo'].value_counts(normalize=True) * 100)

tipo
one timer    36802
recurring    18183
Name: count, dtype: int64
tipo
one timer    66.930981
recurring    33.069019
Name: proportion, dtype: float64

In [22]:
print('no final do ano, 2/3 dos clientes em churn são clientes de passagem')

no final do ano, 2/3 dos clientes em churn são clientes de passagem

# H2.1 - O intervalo entre as compras aumenta antes do churn

Isto é, um cliente se desengaja gradualmente

In [23]:
# pegar as as 3 últimas visitas
base['DATA_ATEND'] = pd.to_datetime(base['DATA_ATEND'])
visitas = base[['CLI_CPF', 'DATA_ATEND']].drop_duplicates().sort_values(['CLI_CPF', 'DATA_ATEND'])

visitas['intervalo'] = visitas.groupby(by=['CLI_CPF'])['DATA_ATEND'].diff().dt.days

visitas

             CLI_CPF DATA_ATEND  intervalo
21138   000068324b7a 2024-01-18        NaN
63230   000068324b7a 2024-02-20       33.0
97691   000068324b7a 2024-03-14       23.0
233921  000068324b7a 2024-06-15       93.0
257006  000068324b7a 2024-07-02       17.0
...              ...        ...        ...
488462  fffc424374da 2024-11-23       40.0
549574  fffc424374da 2024-12-27       34.0
43514   fffcf6606169 2024-02-04        NaN
515368  fffd5abaf0a9 2024-12-08        NaN
497460  fffe8a47ed47 2024-11-29        NaN

[297257 rows x 3 columns]

In [24]:
# ordena as datas das últimas compras pra um cliente de forma decrescente. ex cliente 000068324b7a, última compra é 0, penúltima é 1, 
# ...
# ideia: pegar o intervalo de 0 e 1, 1 e 2, 2 e 3, 3 e 4
visitas['ordem_rev'] = visitas.groupby('CLI_CPF').cumcount(ascending=False)
visitas.head(10)

             CLI_CPF DATA_ATEND  intervalo  ordem_rev
21138   000068324b7a 2024-01-18        NaN          6
63230   000068324b7a 2024-02-20       33.0          5
97691   000068324b7a 2024-03-14       23.0          4
233921  000068324b7a 2024-06-15       93.0          3
257006  000068324b7a 2024-07-02       17.0          2
320827  000068324b7a 2024-08-10       39.0          1
443844  000068324b7a 2024-10-26       77.0          0
389164  0000e45cf057 2024-09-22        NaN          0
199454  0002f692edec 2024-05-24        NaN          6
229275  0002f692edec 2024-06-12       19.0          5

In [25]:
ultimas_compras = visitas[visitas['ordem_rev'] <= 2].pivot(
    index='CLI_CPF',
    columns = 'ordem_rev',
    values='intervalo'
)

ultimas_compras.columns = ['ultimo_intervalo', 'penultimo_intervalo', 'antepenultimo_intervalo']

data_corte = base['DATA_ATEND'].max() - pd.Timedelta(days=90)
ultimas_datas = visitas.groupby('CLI_CPF')['DATA_ATEND'].max()
ultimas_compras['churn'] = ultimas_datas < data_corte

ultimas_compras

,ultimo_intervalo,penultimo_intervalo,antepenultimo_intervalo,churn
CLI_CPF,,,,
000068324b7a,77.0,39.0,17.0,False
0000e45cf057,NaN,NaN,NaN,True
0002f692edec,26.0,23.0,30.0,False
0003384bf59a,NaN,NaN,NaN,False
0005526cbd58,68.0,NaN,NaN,True
...,...,...,...,...
fffc253c49e5,NaN,NaN,NaN,True
fffc424374da,34.0,40.0,7.0,False
fffcf6606169,NaN,NaN,NaN,True
fffd5abaf0a9,NaN,NaN,NaN,False
fffe8a47ed47,NaN,NaN,NaN,False

In [26]:

df_h21 = ultimas_compras.dropna()

# 7. Comparar médias e medianas dos intervalos entre Ativos (False) e Churn (True)
print("--- Médias dos Intervalos (em dias) ---")
print(df_h21.groupby('churn')[['antepenultimo_intervalo', 'penultimo_intervalo', 'ultimo_intervalo']].mean().round(1))

print("\n--- Medianas dos Intervalos (em dias) ---")
print(df_h21.groupby('churn')[['antepenultimo_intervalo', 'penultimo_intervalo', 'ultimo_intervalo']].median())

--- Médias dos Intervalos (em dias) ---
       antepenultimo_intervalo  penultimo_intervalo  ultimo_intervalo
churn
False                     48.3                 48.5              50.6
True                      41.6                 41.6              47.3

--- Medianas dos Intervalos (em dias) ---
       antepenultimo_intervalo  penultimo_intervalo  ultimo_intervalo
churn
False                     33.0                 34.0              36.0
True                      31.0                 32.0              36.0

Resultado não discriminatório entre clientes em churn ou não

# H2.2 categorias influenciam o churn

In [27]:
df_completo = base.merge(base_produtos, on='SKU', how='left')

df_completo.info()

<class 'pandas.DataFrame'>
RangeIndex: 556198 entries, 0 to 556197
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   COD_ATEND     556198 non-null  str
 1   COD_VENDA     556198 non-null  str
 2   COD_FILIAL    556198 non-null  int64
 3   FILIAL        556198 non-null  str
 4   DATA_ATEND    556198 non-null  datetime64[us]
 5   SKU           556198 non-null  int64
 6   UNID          556198 non-null  str
 7   QTD_VENDA     556198 non-null  float64
 8   FATUR_VENDA   556198 non-null  float64
 9   CLI_CPF       556198 non-null  str
 10  NOME_PRODUTO  556198 non-null  str
 11  CATEGORIA     556198 non-null  str
 12  SUBCATEGORIA  556198 non-null  str
dtypes: datetime64[us](1), float64(2), int64(2), str(8)
memory usage: 55.2 MB

In [28]:
threshold

Timestamp('2024-10-02 00:00:00')

In [29]:
resumo_clientes

              visitas ultima_compra  churn       tipo
CLI_CPF
000068324b7a        7    2024-10-26  False  recurring
0000e45cf057        1    2024-09-22   True  one timer
0002f692edec        7    2024-10-22  False  recurring
0003384bf59a        1    2024-10-29  False  one timer
0005526cbd58        2    2024-08-31   True  recurring
...               ...           ...    ...        ...
fffc253c49e5        1    2024-08-10   True  one timer
fffc424374da       11    2024-12-27  False  recurring
fffcf6606169        1    2024-02-04   True  one timer
fffd5abaf0a9        1    2024-12-08  False  one timer
fffe8a47ed47        1    2024-11-29  False  one timer

[102943 rows x 4 columns]

In [30]:
resumo_clientes['recorrente'] = resumo_clientes['visitas'] > 1

In [31]:
df_completo = df_completo.join(resumo_clientes[['churn', 'recorrente']], on='CLI_CPF')

In [32]:
# considerando o estado dos clientes no último dia do ano
df_completo

,COD_ATEND,COD_VENDA,COD_FILIAL,FILIAL,DATA_ATEND,SKU,UNID,QTD_VENDA,FATUR_VENDA,CLI_CPF,NOME_PRODUTO,CATEGORIA,SUBCATEGORIA,churn,recorrente
0,000304564.299.0101042.20240102,000304564.299.0101042.20240102.000009.02,101042,SHOPPING,2024-01-02,9,KG,0.258,18.04,ec0abf3f4220,CAST DE CAJU W4TS TOR C/SAL LUXO KG ...,Castanhas & Oleaginosas,Castanhas de Caju,False,True
1,000374698.258.0101032.20240102,000374698.258.0101032.20240102.000009.10,101032,RUA,2024-01-02,9,KG,0.064,4.50,83d596ee0acf,CAST DE CAJU W4TS TOR C/SAL LUXO KG ...,Castanhas & Oleaginosas,Castanhas de Caju,True,False
2,000383551.256.0101032.20240102,000383551.256.0101032.20240102.000009.02,101032,RUA,2024-01-02,9,KG,0.164,11.49,46f63c18e055,CAST DE CAJU W4TS TOR C/SAL LUXO KG ...,Castanhas & Oleaginosas,Castanhas de Caju,True,False
3,000383533.256.0101032.20240102,000383533.256.0101032.20240102.000009.02,101032,RUA,2024-01-02,9,KG,0.202,14.13,6def1d35e2fe,CAST DE CAJU W4TS TOR C/SAL LUXO KG ...,Castanhas & Oleaginosas,Castanhas de Caju,False,True
4,000432095.257.0101032.20240102,000432095.257.0101032.20240102.000051.06,101032,RUA,2024-01-02,51,KG,0.086,6.87,1576e1a36394,NOZES S/C PARTIDA EXTRA LIGHT KG ...,Castanhas & Oleaginosas,Nozes,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
556193,000396872.299.0101042.20241231,000396872.299.0101042.20241231.024706.03,101042,SHOPPING,2024-12-31,24706,KG,0.172,15.46,1137731f4e6d,DAMASCO DOCE JUMBO KG ...,Frutas,Secas,False,True
556194,000503471.257.0101032.20241231,000503471.257.0101032.20241231.024706.05,101032,RUA,2024-12-31,24706,KG,0.149,13.40,450e762ff3dc,DAMASCO DOCE JUMBO KG ...,Frutas,Secas,False,True
556195,000396715.299.0101042.20241231,000396715.299.0101042.20241231.024706.01,101042,SHOPPING,2024-12-31,24706,KG,0.198,17.80,7c8d2e4be303,DAMASCO DOCE JUMBO KG ...,Frutas,Secas,False,True
556196,000402593.298.0101042.20241231,000402593.298.0101042.20241231.024706.03,101042,SHOPPING,2024-12-31,24706,KG,0.244,21.94,f16ad4e37bb5,DAMASCO DOCE JUMBO KG ...,Frutas,Secas,False,True
556197,000503479.257.0101032.20241231,000503479.257.0101032.20241231.024706.02,101032,RUA,2024-12-31,24706,KG,0.184,16.54,b07b21397e0a,DAMASCO DOCE JUMBO KG ...,Frutas,Secas,False,True

In [33]:
analise_cat = df_completo.groupby('CATEGORIA').apply(lambda g: pd.Series({
    'clientes_unicos': g['CLI_CPF'].nunique(),
    'taxa_churn_geral (%)': (g.drop_duplicates('CLI_CPF')['churn'].mean() * 100).round(1),
    'faturamento_total (R$)': g['FATUR_VENDA'].sum().round(2)
})).sort_values(by='taxa_churn_geral (%)', ascending=False)

print(analise_cat)

                              clientes_unicos  taxa_churn_geral (%)  \
CATEGORIA
Lanchonete                             7527.0                  49.0
Temperos & Condimentos                55445.0                  48.6
Mixes da Casa                         16624.0                  44.3
Superalimentos & Energéticos          10221.0                  42.8
Grãos                                 21538.0                  42.3
Castanhas & Oleaginosas               30615.0                  42.1
Ervas & Chás                           7015.0                  41.4
Azeites & Vinagres                     2777.0                  41.0
Matinais                              17781.0                  40.8
Aperitivos                             9465.0                  40.2
Frutas                                28486.0                  38.2
Conservas                              5732.0                  32.8
Bacalhau & Pescados                   13511.0                  25.6

                              faturamento_total (R$)
CATEGORIA
Lanchonete                                 127054.27
Temperos & Condimentos                     940771.64
Mixes da Casa                              445741.95
Superalimentos & Energéticos               284057.30
Grãos                                      375510.20
Castanhas & Oleaginosas                   1663514.93
Ervas & Chás                                73382.57
Azeites & Vinagres                         105960.17
Matinais                                   227005.13
Aperitivos                                 220907.28
Frutas                                     932519.10
Conservas                                  138752.75
Bacalhau & Pescados                       2313549.64

In [34]:
analise_cat = df_completo.groupby('CATEGORIA').apply(lambda g: pd.Series({
    'clientes_unicos': g['CLI_CPF'].nunique(),
    'taxa_recorrencia (%)': (g.drop_duplicates('CLI_CPF')['recorrente'].mean() * 100).round(1),
    'faturamento_total (R$)': g['FATUR_VENDA'].sum().round(2)
})).sort_values(by='taxa_recorrencia (%)', ascending=False)

print(analise_cat)

                              clientes_unicos  taxa_recorrencia (%)  \
CATEGORIA
Conservas                              5732.0                  76.0
Azeites & Vinagres                     2777.0                  75.2
Matinais                              17781.0                  74.4
Aperitivos                             9465.0                  74.1
Grãos                                 21538.0                  72.4
Frutas                                28486.0                  71.9
Superalimentos & Energéticos          10221.0                  70.6
Castanhas & Oleaginosas               30615.0                  69.5
Ervas & Chás                           7015.0                  69.0
Mixes da Casa                         16624.0                  67.8
Lanchonete                             7527.0                  64.4
Temperos & Condimentos                55445.0                  62.0
Bacalhau & Pescados                   13511.0                  61.2

                              faturamento_total (R$)
CATEGORIA
Conservas                                  138752.75
Azeites & Vinagres                         105960.17
Matinais                                   227005.13
Aperitivos                                 220907.28
Grãos                                      375510.20
Frutas                                     932519.10
Superalimentos & Energéticos               284057.30
Castanhas & Oleaginosas                   1663514.93
Ervas & Chás                                73382.57
Mixes da Casa                              445741.95
Lanchonete                                 127054.27
Temperos & Condimentos                     940771.64
Bacalhau & Pescados                       2313549.64

Bacalhau tem baixa taxa de churn pelo efeito natal. Os itens com maior taxa de recorrência são itens do dia a dia.

# H2.3 Meses com mais feriados apresentam maior taxa de recorrência

In [35]:

base['DATA_ATEND'] = pd.to_datetime(base['DATA_ATEND'])
base['MES'] = base['DATA_ATEND'].dt.month

primeira_compra = base.groupby('CLI_CPF')['DATA_ATEND'].min()
base['primeira_compra'] = base['CLI_CPF'].map(primeira_compra)

# Cliente de retorno: qualquer compra realizada após a sua primeira data histórica
base['is_retorno'] = base['DATA_ATEND'] > base['primeira_compra']

# 3. Métricas mensais
mensal = base.groupby('MES').agg(
    faturamento=('FATUR_VENDA', 'sum'),
    clientes_totais=('CLI_CPF', 'nunique'),
    clientes_retorno=('CLI_CPF', lambda x: x[base.loc[x.index, 'is_retorno']].nunique())
)

# 4. Inserir a contagem de feriados de 2024
feriados_2024 = {
    1: 1, 2: 2, 3: 1, 4: 1, 5: 2, 6: 0,
    7: 0, 8: 0, 9: 1, 10: 1, 11: 3, 12: 1
}
mensal['qtd_feriados'] = mensal.index.map(feriados_2024)

# 5. Visualizar tabela e correlação
print(mensal)

print("\nCorrelação entre Feriados e Clientes de Retorno:")
print(mensal['qtd_feriados'].corr(mensal['clientes_retorno']).round(3))

     faturamento  clientes_totais  clientes_retorno  qtd_feriados
MES
1      395487.73            16949              2611             1
2      411190.68            17440              6318             2
3      839304.32            20367              9568             1
4      490214.50            18959             10749             1
5      543031.77            20325             12561             2
6      497240.68            20033             13188             0
7      549079.07            20921             14198             0
8      611022.15            22481             15779             0
9      548318.71            20740             15026             1
10     632479.42            21675             16091             1
11     838803.47            21194             15728             3
12    1492554.43            22059             16607             1

Correlação entre Feriados e Clientes de Retorno:
-0.121

In [36]:
print("\nCorrelação entre Feriados e Clientes de Retorno:")
print(mensal['qtd_feriados'].corr(mensal['faturamento']).round(3))

Correlação entre Feriados e Clientes de Retorno:
0.108

O faturamento é impactado positivamente pela quantidade de feriados, mas isso é movido pela Páscoa e Natal principalmente. Não há evidência forte o suficiente para explicar que mais clientes voltem na loja num feriado.

# H3 tipo de filial

In [37]:

perfil_filial = base.groupby('CLI_CPF').agg(
    total_visitas=('DATA_ATEND', 'nunique'),
    ultima_compra=('DATA_ATEND', 'max'),
    filiais=('FILIAL', 'unique'),
    faturamento_total=('FATUR_VENDA', 'sum')
)

perfil_filial['churn'] = perfil_filial['ultima_compra'] < threshold
perfil_filial['one_timer'] = perfil_filial['total_visitas'] == 1

# 3. Classificar o canal de preferência do cliente
def definir_canal(filiais):
    if len(filiais) > 1:
        return 'Ambos (Híbrido)'
    return filiais[0]

perfil_filial['tipo_filial'] = perfil_filial['filiais'].apply(definir_canal)

# 4. Tabela comparativa por Tipo de Filial
comparativo_h3 = perfil_filial.groupby('tipo_filial').agg(
    total_clientes=('total_visitas', 'count'),
    taxa_churn_pct=('churn', lambda x: (x.mean() * 100)),
    taxa_one_timer_pct=('one_timer', lambda x: (x.mean() * 100)),
    media_visitas_ano=('total_visitas', 'mean'),
    gasto_medio_anual=('faturamento_total', 'mean')
).round(2)

print(comparativo_h3)

                 total_clientes  taxa_churn_pct  taxa_one_timer_pct  \
tipo_filial
Ambos (Híbrido)            2167           33.41                0.05
RUA                       47200           52.07               47.41
SHOPPING                  53576           55.40               54.69

                 media_visitas_ano  gasto_medio_anual
tipo_filial
Ambos (Híbrido)               5.05             132.79
RUA                           3.12              77.73
SHOPPING                      2.60              72.65

shoppings têm mais clientes one timers. clientes de rua visitam mais. clientes multicanais têm menos taxa de churn e mais visitas por ano

# Conclusão

| Hipótese | Enunciado | Veredito | Evidência Numérica Principal |
| :--- | :--- | :---: | :--- | 
| **Definição de Churn** | Churn ocorre após **90 dias** sem compras | ✅ **Confirmada** | • Mediana de recompra: **29 dias** (ciclo mensal)<br>• **83,88%** das recompras ocorrem em até 90 dias |
| **H1: De passagem vs Desengajados** | No churn há clientes de compra única (*one-timers*) e recorrentes que abandonaram | ✅ **Confirmada** | • 50,20% da base é de compra única<br>• Entre os clientes em churn: **66,9% são *one-timers*** e **33,1% são recorrentes** | 
| **H2.1: Frequência** | O intervalo entre compras aumenta progressivamente antes do churn | ❌ **Refutada** | • 54% dos clientes em churn aumentaram o intervalo antes de sumir<br>• **51% dos clientes ativos também aumentaram** | 
| **H2.2: Comportamental (Categorias)** | Categorias de rotina/despensa geram maior fidelização do que itens ocasionais | ✅ **Confirmada** | • **Maior fidelidade:** Conservas (76%), Azeites (75%), Matinais (74%) e Grãos (72%)<br>• **Maior churn:** Lanchonete (49%) e Temperos (48%) | 
| **H2.3: Feriados** | Meses com mais feriados atraem mais clientes de volta | ❌ **Refutada** | • Correlação nula/negativa ($r = -0,12$)<br>• Meses com **zero feriados** (Jun, Jul, Ago) tiveram alto retorno (~13k a 15k clientes) | 
| **H3: Tipo de Filial** | O tipo de filial (`SHOPPING` vs `RUA`) influencia o churn e a frequência | ✅ **Confirmada** | • **Shopping:** 55,4% churn \| 54,7% *one-timers* \| 2,6 visitas/ano<br>• **Rua:** 52,1% churn \| 47,4% *one-timers* \| 3,1 visitas/ano<br>• **Ambos (Híbridos):** 33,4% churn \| 0% *one-timers* \| 5,1 visitas/ano \| Gasto +82% |